// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using oriontek.Models;

#nullable disable

namespace oriontek.Migrations
{
    [DbContext(typeof(oriontekContext))]
    [Migration("20220607205920_MigrarionInitial")]
    partial class MigrarionInitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("oriontek.Models.Client", b =>
                {
                    b.Property<int>("Idclient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idclient");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idclient"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Idclient");

                    b.ToTable("client", (string)null);
                });

            modelBuilder.Entity("oriontek.Models.Direccion", b =>
                {
                    b.Property<int>("Iddirecc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iddirecc");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Iddirecc"), 1L, 1);

                    b.Property<string>("Direccion1")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("direccion");

                    b.Property<int?>("Idcli")
                        .HasColumnType("int")
                        .HasColumnName("idcli");

                    b.HasKey("Iddirecc");

                    b.HasIndex("Idcli");

                    b.ToTable("direccion", (string)null);
                });

            modelBuilder.Entity("oriontek.Models.Direccion", b =>
                {
                    b.HasOne("oriontek.Models.Client", "IdcliNavigation")
                        .WithMany("Direccions")
                        .HasForeignKey("Idcli")
                        .HasConstraintName("FK_direccion_client");

                    b.Navigation("IdcliNavigation");
                });

            modelBuilder.Entity("oriontek.Models.Client", b =>
                {
                    b.Navigation("Direccions");
                });
#pragma warning restore 612, 618
        }
    }
}
